### ISSUE TITLE
Change Siren Field "Prompt" to "Title"

### ISSUE THREAD

**Issue by kevinswiber** [JoaoRXFernandes/AnHypermediaEngine#1]
Hi there.

Cool project!

I just wanted to point out that Siren uses a `title` attribute on a field to accomplish what I think you're going for with `prompt`.

Reference: https://github.com/kevinswiber/siren#title-4

**Comment by JoaoRXFernandes** [comment]
Hi @kevinswiber, 

Great to see you here and really glad you like the project!

Thanks for pointing that out, I guess I was thinking of @mamund Collection+Json and got it confused.

Please don't hesitate.

Cheers!
